name: CI - Build & Test
on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '**.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i "s|{{PATHTOREPO}}|$(pwd)|" packages/k8s/tests/test-kind.yaml
        name: Setup kind cluster yaml config
      - uses: helm/kind-action@v1.2.0
        with:
          config: packages/k8s/tests/test-kind.yaml
      - run: npm install
        name: Install dependencies
      - run: npm run bootstrap
        name: Bootstrap the packages
      - run: npm run build-all
        name: Build packages
      - run: npm run format-check
      - name: Check linter
        run: |
          npm run lint
          git diff --exit-code -- ':!packages/k8s/tests/test-kind.yaml'
      - name: Run tests
        run: npm run test